// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi_LaminacionBLBP.Models;

namespace WebApi_LaminacionBLBP.Migrations
{
    [DbContext(typeof(LamblbpDetailContext))]
    [Migration("20201012025618_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.2.6-servicing-10079")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("WebApi_LaminacionBLBP.Models.LamblbpDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<byte>("Cantidadturnos")
                        .HasColumnType("tinyint");

                    b.Property<DateTime>("EstampaTiempo")
                        .HasColumnType("datetime");

                    b.Property<DateTime>("Fechalaminador")
                        .HasColumnType("date");

                    b.Property<float>("LaminadorBarrasperdidasUltimahora")
                        .HasColumnType("real");

                    b.Property<short>("LaminadorPalanquillaslaminadasUltimahora")
                        .HasColumnType("smallint");

                    b.Property<DateTime>("Modificado")
                        .HasColumnType("datetime");

                    b.Property<string>("Modificadopor")
                        .IsRequired()
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Planta")
                        .IsRequired()
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Plantel")
                        .IsRequired()
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Turno")
                        .IsRequired()
                        .HasColumnType("nvarchar(4000)");

                    b.HasKey("Id");

                    b.ToTable("LamblbpDetails");
                });
#pragma warning restore 612, 618
        }
    }
}
